select * from  client where  length(FirstName) < 6;
select * from client where city='Lviv';
select * from client where education = 'high' order by lastname;   
select * from  application where idapplication>0 order by idapplication desc limit 5;
select * from client where lastname like '%ov' or '%ova';
select * from department where departmentcity='kyiv';
select * from  client order by firstname;
select * from  bank.application where sum > 5000;
select count(*) from bank.client; select count(*) from bank.client where city='lviv';
select max(sum), FirstName, LastName from application join client ON application.Client_idClient = client.idClient group by client.idClient;
select count(client.idClient), firstname, lastname from application join client on application.Client_idClient = client.idClient group by client.idClient;
select max(sum), min(sum) from application;
select count(client.idClient) from application join client on application.Client_idClient = client.idClient where client.Education like 'high' group by client.idClient;
select max(result.avgkredit), firstname, lastname from (select avg(application.sum) AS avgkredit, firstname, lastname from application join client on application.Client_idClient = client.idClient group by client.idClient) AS result;
/*15*/select maxumym.iddepartment, max(maxumym.kredit), maxumym.departmentcity from (select department.iddepartment, department.departmentcity, sum(application.sum) AS kredit from department join client on  department.iddepartment=client.department_iddepartment join application on application.Client_idClient = client.idClient group by department.iddepartment) AS maxumym;
/*15*/select department.iddepartment, department.departmentcity, sum(application.sum) AS kredit from department join client on  department.iddepartment=client.department_iddepartment join application on application.Client_idClient = client.idClient group by department.iddepartment order by kredit desc limit 1;
/*16*/select max(sum), departmentcity from department join client on  department.iddepartment=client.department_iddepartment join application on application.Client_idClient = client.idClient;
/*17*/update application set sum = 6000 where client_idclient in (select client.idclient from client where education = 'high'); select * from application;
/*18*/update client set department_iddepartment = 1 where department_iddepartment = 3; select * from client; 
/*19*/delete  from application where creditstate = 'returned'; select * from application; 
/*20*/delete from application where client_idclient in (select client.idclient from client where substring(lastname, 2, 1) in ('e','o'));
/*20*/delete from client where substring(lastname, 2, 1) in ('e','o');select * from client;
/*21*/select departmentcity,sum from department join client on  department.iddepartment=client.department_iddepartment join application on application.Client_idClient = client.idClient where sum > 5000 and departmentcity = 'Lviv';
/*22*/select * from client join application on application.Client_idClient = client.idClient   where sum > 5000 and CreditState = 'returned';
/*23*/select max(sum), Firstname, Lastname from application join client on application.Client_idClient = client.idClient where CreditState = 'not returned';
/*24*/select min(sum), Firstname, Lastname from application join client on application.Client_idClient = client.idClient;
/*25*/select sum from application where sum > (select avg(sum) from application limit 1);
/*26*/select client.* from client join (select count(*) as maxumym, city from application join client on application.Client_idClient = client.idClient group by client.idClient order by maxumym desc limit 1) AS result on result.city = client.city; 
/*27*/select count(*) as maxumym, city from application join client on application.Client_idClient = client.idClient group by client.idClient order by maxumym desc limit 1;

		set sql_safe_updates = 0;
		set sql_safe_updates = 1;